export const FETCH_NEWS_INIT = 'FETCH_NEWS_INIT';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';
export const FETCH_NEWS = 'FETCH_NEWS';

export const FETCH_TAGS = 'FETCH_TAGS';
